### PR TITLE
fix(dracut.sh): use only compressor that kernel supports

### LINKED ISSUE #378: dracut does not check for kernel compression support
**Describe the bug**

When using zstd compression, dracut checks that the kernel supports zstd compressed initrds (`CONFIG_RD_ZSTD`). But dracut does not do this check for all the other possible compression formats. So you might end up with a xz or gzip compressed initrd that cannot be read by the kernel. Please also check those kernel configs:

```
CONFIG_RD_GZIP
CONFIG_RD_BZIP2
CONFIG_RD_LZMA
CONFIG_RD_XZ
CONFIG_RD_LZO
CONFIG_RD_LZ4
```

**Dracut version**
102

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Follows up on:
- https://github.com/dracut-ng/dracut-ng/pull/520
- https://github.com/dracut-ng/dracut-ng/pull/541

And fixes:
- https://github.com/dracut-ng/dracut-ng/issues/378

Note #520 contains a fix for the `check_kernel_config` function and should be merged first.

Closes: https://github.com/dracut-ng/dracut-ng/issues/378

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #378

### CODE REVIEW

File: dracut.sh [hunk 1]
```diff
@@ -2335,23 +2335,59 @@ else
     DRACUT_KERNEL_RD_ZSTD=
```
Comment (bdrung) [inline dracut.sh:2335]: Setting `DRACUT_KERNEL_RD_ZSTD` can be dropped.

File: dracut.sh [hunk 2]
```diff
@@ -2335,23 +2335,59 @@ else
...
 fi
 
-if [[ $compress == $DRACUT_COMPRESS_ZSTD* && ! $DRACUT_KERNEL_RD_ZSTD ]]; then
-    dwarn "Kernel has no zstd support compiled in."
-    compress=
-fi
+
+check_kernel_compress_support() {
+    local kern_compress_config
+    case $1 in
```
Comment (bdrung) [inline dracut.sh:2341]: issue: The `DRACUT_COMPRESS_*` variables could be set by the user. In that case this case statement would fail.

suggestion: Tie the `kern_compress_config` with the `DRACUT_COMPRESS_*` variables (probably at the `handle compression options` section to ensure they stay in sync if compressors are added/removed).

**Review by bdrung — CHANGES_REQUESTED** [review]
Thanks for working on it!

File: dracut.sh (hunk 2 above)
Comment (AndrewAmmerlaan) [reply dracut.sh:2334]: I'm not sure I understand how that resolves the issue. If the user sets e.g. `DRACUT_COMPRESS_BZIP2=foo` then there still is no way to know for sure which kernel config option should be checked. Probably it is `CONFIG_RD_BZIP2`, but the fact that this variable was set by the user does not necessarily mean that `compress=bzip2` as well.  And regardless of what compression type we are going to use, all of these variables will be populated so checking which ones are set does not help here.

This is why I made the `*)` case not fail fatally. If `compress=` is set to some command that we do not know, we simply warn but still try and hope for the best.

Comment (bdrung) [reply dracut.sh:2334]: The contract with the user is that `DRACUT_COMPRESS_BZIP2` points to a bzip2 compressor. This could be an uncommon path like `DRACUT_COMPRESS_BZIP2=foo/bar/bzip2` or some compatible command. So `CONFIG_RD_BZIP2` should be checked in that case.

Comment (AndrewAmmerlaan) [reply dracut.sh]: How about this?

Now it checks for the correct kernel config option for:
- `DRACUT_COMPRESS_GZIP=/usr/bin/gzip  ./dracut.sh --kver 6.10.3-gentoo-dist /tmp/test.img -f --compress='/usr/bin/gzip -9 -n' `
- `DRACUT_COMPRESS_GZIP=/usr/bin/gzip  ./dracut.sh --kver 6.10.3-gentoo-dist /tmp/test.img -f --gzip `
- `./dracut.sh --kver 6.10.3-gentoo-dist /tmp/test.img -f --compress='/usr/bin/gzip -9 -n' `
- `./dracut.sh --kver 6.10.3-gentoo-dist /tmp/test.img -f --gzip `

That should cover all cases right?

**Review by pvalena — APPROVED** [review]
LGTM, although I've not tested the code.

File: dracut.sh (hunk 2 above)
Comment (bdrung) [reply dracut.sh]: Yes, this should cover most (the normal) cases.

**Review by bdrung — APPROVED** [review]
I would have preferred an associative array to just store the mapping:
```bash
declare -A compressor2config
compressor2config["$DRACUT_COMPRESS_BZIP2"] = CONFIG_RD_BZIP2
compressor2config["$DRACUT_COMPRESS_LBZIP2"] = CONFIG_RD_BZIP2
compressor2config["$DRACUT_COMPRESS_LZMA"] = CONFIG_RD_LZMA
[...]
    for i in $DRACUT_COMPRESS_ZSTD [...]; do
        check_kernel_config "compressor2config[$i]"
        [...]
```

But the user can specify an arbitrary compress command.

**Review by Conan-Kudo — APPROVED** [review]
