### PR TITLE
fix(systemd-sysusers): remove (g)shadow created by systemd-sysusers

### LINKED ISSUE #1242: cpio: etc/gshadow: Cannot open: Permission denied
**Describe the bug**
initramfs build failure

**Distribution used**
Arch Linux

**Dracut version**
Regression bisected to v106 commit f3dacc013d90bd2c

**Init system**
systemd

**To Reproduce**

~/dracut-ng/dracut.sh -l --force --verbose --no-hostonly --show-modules --kver=6.14.0-rc1-00047-g0a14566be090-dirty --kmoddir ./qbuild/mkosi.extra/lib/modules/6.14.0-rc1-00047-g0a14566be090-dirty/ --kernel-image ./vmlinux --add 'bash systemd kernel-modules fs-lib' --omit 'iscsi fcoe fcoe-uefi' --omit-drivers 'nfit libnvdimm nd_pmem' ./qbuild/mkosi.extra/boot/initramfs-6.14.0-rc1-00047-g0a14566be090-dirty.img 

**Expected behavior**

initramfs is built

### PR DESCRIPTION
**Pull request by jozzsi**
## Changes

The files `shadow` and `gshadow` do NOT exist when using the commit before f3dacc0.

This commit restores the earlier behavior.

## Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1242

### CODE REVIEW

**Review by marc-hb — COMMENTED** [review]
I have no idea whether this is the right approach or not but this does fix the build for me.

File: modules.d/99systemd-sysusers/module-setup.sh [hunk 1]
```diff
@@ -23,4 +23,7 @@ install() {
         set -o pipefail
         systemd-sysusers --root="$initdir" 2>&1 >&3 | grep -v "^Creating " >&2
     } 3>&1
+
+    # delete shadow files created by systemd-sysusers
+    rm -f "$initdir/etc/shadow" "$initdir/etc/gshadow"
```
Comment (marc-hb) [inline modules.d/99systemd-sysusers/module-setup.sh:28]: Maybe the comment should explain why? Not just paraphrase the code.

File: modules.d/99systemd-sysusers/module-setup.sh [hunk 2]
```diff
@@ -23,4 +23,7 @@ install() {
         set -o pipefail
         systemd-sysusers --root="$initdir" 2>&1 >&3 | grep -v "^Creating " >&2
     } 3>&1
+
+    # delete shadow files as initramfs is not designed to ask for a non-root user password interactively
```
Comment (marc-hb) [inline modules.d/99systemd-sysusers/module-setup.sh:27]:
```suggestion
    # delete shadow files as initramfs is not designed to ask for a non-root user password
    # interactively and their permissions crashes the build.
```

Comment (marc-hb) [reply modules.d/99systemd-sysusers/module-setup.sh:27]: Did you check #1242? It may be "just" a missing permission but there's no image produced. "crash" = showstopper = nothing works.

**Comment by zboszor** [comment]
> @zboszor . Szia. I can see that you also worked on this bug with a different approach. Do you have any feedback/thoughts on this PR ? I am personally open to both approaches, but slightly prefer to this PR due to less complexity (less conditionals).

I think this is better than my approach, assuming the (empty?) passwords in `/etc/{g,}shadow` are not used during boot from the initramfs.

**Comment by chewi** [comment]
Does this not break the root password set in 99base for the emergency console in host-only mode?

**Comment by marc-hb** [comment]
> This PR has a dependency on #1211

The chain of dependency now leads to (pretty big) #1194.  I don't know anything about dracut but I find the lack of "urgency" somewhat disappointing for such a critical bug. I bisected, pinpointed and filed regression #1242 two months ago now. I mean it's disappointing that no "quick" and temporary fix (like this one) was possible in the mean time. It's common to see quick and small fixes reverted in the PR of the "real" and bigger fix - but not here? I hope this won't increase the span of buggy releases too much. I see v107 was just released - apparently with this bug? Release notes don't have any list of "known issues". 

I'm also wondering about test coverage... I didn't feel like I was doing anything extraordinary in #1242, was I? Reproduction is a single `dracut` command. How come no one else saw this?

> Temporarily closing, plan to reopen

Demoting to a GitHub "draft" works well in situations like this one. Drafts cannot be merged and can very easily be filtered out. My 2 cents; you do you.

**Comment by marc-hb** [comment]
>  I think most people run Dracut as root anyway, so maybe that's why this hasn't been treated so urgently. 

There's "people" and there's CI/automation. I see a lot of checks run in every PR, which looks nice. How come none of these caught this? Do they all run as root too?

> Maybe they shouldn't, but that's another matter.

"People" is another matter. CI is not.

**Review by marc-hb — APPROVED** [review]

**Review by bdrung — APPROVED** [review]
Approved from my side under one condition: Someone verified that this change does not break root password set in base module for the emergency console in host-only mode.

**Comment by marc-hb** [comment]
I stand corrected, thanks @jozzsi for your patience. I clearly spent too much time playing with scripts and not enough time looking at documentation.

I would have placed https://dracut-ng.github.io/dracut-ng/developer/hacking.html#_testsuite before commit messages, coding style and code of conduct but that's just me :-)

**Comment by marc-hb** [comment]
>  Having a test/README.md sounds like a good idea. It can point to the right location or just be a symlink.

- #1454
