### PR TITLE
fix(crypt): use systemd generator for setting the timeout

### LINKED ISSUE #2307: Test 72 "NBD root=LABEL=dracut netroot=nbd:IP:port" fails on slow systems: dev-nbd0.device runs into a 90 second timeout
**Describe the bug**

Test 72 "NBD root=LABEL=dracut netroot=nbd:IP:port" can fail on slow architectures.

```
603s [   36.841605] dracut-cmdline[178]: + set_systemd_timeout_for_dev /dev/nbd0
[...]
603s [   37.015613] dracut-cmdline[178]: + mkdir -p /etc/systemd/system/dev-nbd0.device.d
603s [   37.020616] dracut-cmdline[178]: + echo [Unit]
603s [   37.025872] dracut-cmdline[178]: + echo JobTimeoutSec=infinity
603s [   37.031417] dracut-cmdline[178]: + echo JobRunningTimeoutSec=infinity
603s [   37.036838] dracut-cmdline[178]: + type mark_hostonly
603s [   37.043508] dracut-cmdline[178]: + _needreload=1
603s [   37.047966] dracut-cmdline[178]: + [ -z  ]
603s [   37.055568] dracut-cmdline[178]: + [ 1 = 1 ]
603s [   37.060790] dracut-cmdline[178]: + [ -z  ]
603s [   37.065785] dracut-cmdline[178]: + /sbin/initqueue --onetime --unique --name daemon-reload systemctl daemon-reload
[...]
[ TIME ] Timed out waiting for device dev-nbd0.device - /dev/nbd0.↵
679s [DEPEND] Dependency failed for systemd-cryp…0e2d54-ab3c-44b1-b289-7e1921480385.
679s [DEPEND] Dependency failed for cryptsetup.target - Local Encrypted Volumes.
679s [  113.311607] systemd[1]: 5:185mdev-nbd0.device: Job dev-nbd0.device/start timed out.
679s [  113.332671] systemd[1]: Timed out waiting for device dev-nbd0.device - /dev/nbd0.
[...]
751s          Starting dracut-initqueue.service - dracut initqueue hook...
[...]
822s [  255.665608] dracut-initqueue[495]: + /usr/bin/systemctl daemon-reload
[...]
835s [  269.333700] systemd[1]: Reload requested from client PID 593 ('systemctl') (unit dracut-initqueue.service)...
835s [  269.378921] systemd[1]: Reloading...
894s [  328.119996] systemd[1]: Reloading finished in 67715 ms.
```

`parse-crypt.sh` calls `set_systemd_timeout_for_dev /dev/nbd0` which correctly creates the `timeout.conf` config. But for this configuration to take action, the systemd daemon needs to be reloaded. This call is added to the initqueue. Because the system is slow, `dev-nbd0.device` times out before the systemd daemon is reloaded.

**Distribution used**
Debian unstable and Ubuntu resolute

**Dracut version**
110

**Init system**
systemd

**To Reproduce**
Run test 72 on a very slow system.

### PR DESCRIPTION
**Pull request by bdrung**
Test 72 "NBD root=LABEL=dracut netroot=nbd:IP:port" can fail on slow architectures.

```
603s [   36.841605] dracut-cmdline[178]: + set_systemd_timeout_for_dev /dev/nbd0
[...]
603s [   37.015613] dracut-cmdline[178]: + mkdir -p /etc/systemd/system/dev-nbd0.device.d
603s [   37.020616] dracut-cmdline[178]: + echo [Unit]
603s [   37.025872] dracut-cmdline[178]: + echo JobTimeoutSec=infinity
603s [   37.031417] dracut-cmdline[178]: + echo JobRunningTimeoutSec=infinity
603s [   37.036838] dracut-cmdline[178]: + type mark_hostonly
603s [   37.043508] dracut-cmdline[178]: + _needreload=1
603s [   37.047966] dracut-cmdline[178]: + [ -z  ]
603s [   37.055568] dracut-cmdline[178]: + [ 1 = 1 ]
603s [   37.060790] dracut-cmdline[178]: + [ -z  ]
603s [   37.065785] dracut-cmdline[178]: + /sbin/initqueue --onetime --unique --name daemon-reload systemctl daemon-reload
[...]
[ TIME ] Timed out waiting for device dev-nbd0.device - /dev/nbd0.
679s [DEPEND] Dependency failed for systemd-cryp…0e2d54-ab3c-44b1-b289-7e1921480385.
679s [DEPEND] Dependency failed for cryptsetup.target - Local Encrypted Volumes.
679s [  113.311607] systemd[1]: dev-nbd0.device: Job dev-nbd0.device/start timed out.
679s [  113.332671] systemd[1]: Timed out waiting for device dev-nbd0.device - /dev/nbd0.
[...]
751s          Starting dracut-initqueue.service - dracut initqueue hook...
[...]
822s [  255.665608] dracut-initqueue[495]: + /usr/bin/systemctl daemon-reload
[...]
835s [  269.333700] systemd[1]: Reload requested from client PID 593 ('systemctl') (unit dracut-initqueue.service)...
835s [  269.378921] systemd[1]: Reloading...
894s [  328.119996] systemd[1]: Reloading finished in 67715 ms.
```

`parse-crypt.sh` calls `set_systemd_timeout_for_dev /dev/nbd0` which correctly creates the `timeout.conf` config. But for this configuration to take action, the systemd daemon needs to be reloaded. This call is added to the initqueue. Because the system is slow, `dev-nbd0.device` times out before the systemd daemon is reloaded.

Move the systemd config generating code into a systemd generator. Then calling `systemctl daemon-reload` is not needed.

Fixes: https://github.com/dracut-ng/dracut-ng/issues/2307
Bug-Ubuntu: https://launchpad.net/bugs/2143264

This merge request depends on https://github.com/dracut-ng/dracut-ng/pull/2310

### Checklist
- [x] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

### CODE REVIEW

**Review by Conan-Kudo — APPROVED** [review]

File: modules.d/70crypt/module-setup.sh [hunk 1]
```diff
@@ -85,7 +85,9 @@ install() {
     fi
 
     inst_hook cmdline 30 "$moddir/parse-crypt.sh"
-    if ! dracut_module_included "systemd"; then
+    if dracut_module_included "systemd"; then
```
Comment (devkontrol) [inline modules.d/70crypt/module-setup.sh:88]: Would it be possible (and would it make sense) to move `crypt-generator.sh` to systemd-cryptsetup dracut module instead ?

Comment (bdrung) [reply modules.d/70crypt/module-setup.sh:88]: Good question. Do we support using the crypt module without systemd-cryptsetup when using systemd?

Comment (devkontrol) [reply modules.d/70crypt/module-setup.sh:88]: Yes, we do, so than I think best to keep the PR as is !

**Review by devkontrol — APPROVED** [review]
