### PR TITLE
test(NFS): use test dracut modules

### LINKED ISSUE #1534: TEST-72-NBD fails in test_check if KVERSION is unset
test_check in TEST-72-NBD:
```sh
    if ! modinfo -k "$KVERSION" nbd &> /dev/null; then
        echo "Kernel module nbd does not exist"
        return 1
    fi
```

A recent commit removed setting `KVERSION`. So this check does not work any more and `set -u` will cause it to fail.

@jozzsi

### PR DESCRIPTION
**Pull request by jozzsi**
## Changes

Make use of test dracut modules and configuration and make the test consistent with the rest of the CI.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Partially Fixes #1534

### CODE REVIEW

File: test/TEST-60-NFS/test.sh [hunk 1]
```diff
@@ -314,26 +266,18 @@ test_setup() {
     cp ./client-init.sh "$initdir"/sbin/init
 
     # second, install the files needed to make the root filesystem
```
Comment (bdrung) [inline test/TEST-60-NFS/test.sh:268]: Is that comment still needed?

Comment (jozzsi) [reply test/TEST-60-NFS/test.sh:268]: https://github.com/dracut-ng/dracut-ng/pull/1545/files
