### PR TITLE
test(DMSQUASH): fix autooverlay test false positive and setup

### LINKED ISSUE #2054: Checking for dracut-autooverlay-success always succeeds
**Describe the bug**

Found while reviewing https://github.com/dracut-ng/dracut-ng/pull/2041: TEST-30-DMSQUASH checks for the presence of `dracut-autooverlay-success` in `root.img`. This tests always succeeds because it finds this string in the `test-init.sh` file which is also included in the root image.

### PR DESCRIPTION
**Pull request by nadzyah**
## Changes

The autooverlay test was always passing due to multiple issues:

* The test searched for the marker string in the entire root.img, but the string also existed literally in `test-init.sh` embedded in the first partition, causing a false positive. Fix by extracting and searching only the second (overlay) partition
* `test-init.sh` tried to read `/proc/cmdline` but `/proc` was not mounted and the directory did not exist. Fix by creating and mounting `/proc` temporarily
* The test disk image contained raw rootfs instead of the live structure (LiveOS/rootfs.img), so FSIMG was empty and `do_live_overlay()` was never called. Fix by using the live structure on disk
* Add `sync` after writing the marker to ensure it is flushed to the persist partition before shutdown

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [x] I am providing new code and test(s) for it

Fixes #2054

### CODE REVIEW

File: test/TEST-30-DMSQUASH/test-init.sh [hunk 1]
```diff
@@ -1,10 +1,18 @@
...
+# Mount /proc temporarily to check kernel cmdline (it doesn't exist yet in this minimal rootfs)
+mkdir -p /proc
+mount -t proc proc /proc
+
 if grep -qF ' rd.live.overlay=LABEL=persist ' /proc/cmdline; then
     # Writing to a file in the root filesystem lets test_run() verify that the autooverlay module successfully created
     # and formatted the overlay partition and that the dmsquash-live module used it when setting up the rootfs overlay.
     echo "dracut-autooverlay-success" > /overlay-marker
+    # Ensure the marker is flushed to disk before shutdown
+    sync
```
Comment (bdrung) [inline test/TEST-30-DMSQUASH/test-init.sh]: you can specify the file that you want to have synced.

**Review by LaszloGombos — DISMISSED** [review]

**Review by Conan-Kudo — DISMISSED** [review]

File: test/TEST-30-DMSQUASH/test.sh [hunk 2]
```diff
@@ -101,7 +106,8 @@ EOF
 
     rm -f "$TESTDIR/ext4.img"
     truncate -s "$((512 * 652688))" "$TESTDIR/ext4.img"
-    mkfs.ext4 -q -L dracut -d "$TESTDIR"/rootfs/ "$TESTDIR"/ext4.img
+    # Use the live structure (with LiveOS/rootfs.img squashfs) instead of raw rootfs
+    mkfs.ext4 -q -L dracut -d "$TESTDIR"/live/ "$TESTDIR"/ext4.img
```
Comment (bdrung) [inline test/TEST-30-DMSQUASH/test.sh:110]: FTR: Took me some time to understand. I searched the history and found commit cb36b8f8d1a3d481a6cf15efefd823052950d6ff that introduced the regression during a restructuring.

**Review by bdrung — DISMISSED** [review]
As mentioned, this PR needs a rebase. The bullet points in the commit message indicate that the commit does multiple atomic changes in a single commit. I'll let this slide this time.

File: test/TEST-30-DMSQUASH/test.sh (hunk 2 above)
Comment (jozzsi) [reply test/TEST-30-DMSQUASH/test.sh:110]: Thanks @bdrung

**Comment by nadzyah** [comment]
Thanks @bdrung and @Conan-Kudo for the review. I've rebased my changes and split commits into atomic ones. Let me know if you want me to fix something else

**Comment by bdrung** [comment]
LGTM. Can you add "Fixes: https://github.com/dracut-ng/dracut-ng/issues/2054" to the last commit.

**Review by bdrung — APPROVED** [review]

**Review by LaszloGombos — APPROVED** [review]
