### PR TITLE
fix: place dracut generated cmdline conf files in the 10-49 range

### LINKED ISSUE #1489: Modules write /etc/cmdline.d/*.conf using the old number
Some modules used to write cmdline conf files prefixed with their module number (others didn't for a reason), but since the new order was introduced, they still use the old one.

Full list, including those that don't need to be changed:

```
> grep -r -n -E 'cmdline.d/[0-9][0-9].*conf' modules.d
modules.d/35network-legacy/parse-ip-opts.sh:133:            >> /etc/cmdline.d/80-enx.conf
modules.d/35network-manager/nm-config.sh:10:    echo rd.neednet >> /etc/cmdline.d/35-neednet.conf
modules.d/45net-lib/net-lib.sh:239:    echo "ifname=$name$num:$mac" >> /etc/cmdline.d/45-ifname.conf
modules.d/45net-lib/net-lib.sh:358:    ) >> /etc/cmdline.d/40-ibft.conf
modules.d/68cms/cmsifup.sh:31:} > /etc/cmdline.d/80-cms.conf
modules.d/69cio_ignore/module-setup.sh:36:        [[ $_cio_accept ]] && printf "%s\n" "$_cio_accept" >> "${initdir}/etc/cmdline.d/01cio_accept.conf"
modules.d/70btrfs/module-setup.sh:35:    printf "%s\n" "$(cmdline)" > "${initdir}/etc/cmdline.d/00-btrfs.conf"
modules.d/70crypt/module-setup.sh:84:        [[ $_cryptconf ]] && printf "%s\n" "$_cryptconf" >> "${initdir}/etc/cmdline.d/90crypt.conf"
modules.d/70dmraid/module-setup.sh:71:        [[ $_raidconf ]] && printf "%s\n" "$_raidconf" >> "${initdir}/etc/cmdline.d/90dmraid.conf"
modules.d/70lvm/module-setup.sh:56:        [[ $_lvmconf ]] && printf "%s\n" "$_lvmconf" >> "${initdir}/etc/cmdline.d/90lvm.conf"
modules.d/70mdraid/module-setup.sh:76:        [[ $_raidconf ]] && printf "%s\n" "$_raidconf" >> "${initdir}/etc/cmdline.d/90mdraid.conf"
modules.d/70multipath/module-setup.sh:147:        [[ $_conf ]] && echo "$_conf" >> "${initdir}/etc/cmdline.d/90multipath.conf"
modules.d/73zipl/install_zipl_cmdline.sh:21:    cp ${MNT}/dracut-cmdline.conf /etc/cmdline.d/99zipl.conf
modules.d/73zipl/install_zipl_cmdline.sh:33:if [ -f /etc/cmdline.d/99zipl.conf ]; then
modules.d/73zipl/module-setup.sh:64:        [[ $_zipl ]] && printf "%s\n" "$_zipl" > "${initdir}/etc/cmdline.d/91zipl.conf"
modules.d/74fcoe-uefi/parse-uefifcoe.sh:34:    print_fcoe_uefi_conf "$i" > /etc/cmdline.d/40-fcoe-uefi.conf && break
modules.d/74fcoe/module-setup.sh:112:        [[ $_fcoeconf ]] && printf "%s\n" "$_fcoeconf" >> "${initdir}/etc/cmdline.d/95fcoe.conf"
modules.d/74iscsi/module-setup.sh:204:        [[ $_iscsiconf ]] && printf "%s\n" "$_iscsiconf" >> "${initdir}/etc/cmdline.d/95iscsi.conf"
modules.d/74lunmask/module-setup.sh:66:            printf "%s\n" "$_lunmask" >> "${initdir}/etc/cmdline.d/95lunmask.conf"
modules.d/74nfs/module-setup.sh:87:        [[ $_netconf ]] && printf "%s\n" "$_netconf" >> "${initdir}/etc/cmdline.d/95nfs.conf"
modules.d/74nvmf/parse-nvmf-boot-connections.sh:217:    done >> /etc/cmdline.d/40-nbft.conf
modules.d/74nvmf/parse-nvmf-boot-connections.sh:226:    rm -f /etc/cmdline.d/95nvmf-args.conf
modules.d/74nvmf/module-setup.sh:143:        [[ "$_nvmf_args" ]] && printf "%s" "$_nvmf_args" >> "${initdir}/etc/cmdline.d/95nvmf-args.conf"
modules.d/74resume/module-setup.sh:66:        [[ $_resumeconf ]] && printf "%s\n" "$_resumeconf" >> "${initdir}/etc/cmdline.d/95resume.conf"
modules.d/74rootfs-block/module-setup.sh:70:        [[ $_journaldev ]] && printf "%s\n" "$_journaldev" >> "${initdir}/etc/cmdline.d/95root-journaldev.conf"
modules.d/74rootfs-block/module-setup.sh:73:        [[ $_rootdev ]] && printf "%s\n" "$_rootdev" >> "${initdir}/etc/cmdline.d/95root-dev.conf"
modules.d/77dracut-systemd/dracut-cmdline-ask.sh:21:    [ -n "$line" ] && printf -- "%s\n" "$line" >> /etc/cmdline.d/99-cmdline-ask.conf
modules.d/77dracut-systemd/dracut-cmdline.sh:12:    [ -f /etc/cmdline.d/99-cmdline-ask.conf ] && mv /etc/cmdline.d/99-cmdline-ask.conf /tmp/99-cmdline-ask.conf
modules.d/77dracut-systemd/dracut-cmdline.sh:15:    [ -f /tmp/99-cmdline-ask.conf ] && mv /tmp/99-cmdline-ask.conf /etc/cmdline.d/99-cmdline-ask.conf
modules.d/80base/init.sh:118:        echo "$line" >> /etc/cmdline.d/99-cmdline-ask.conf
modules.d/80base/init.sh:123:    [ -f /etc/cmdline.d/99-cmdline-ask.conf ] && mv /etc/cmdline.d/99-cmdline-ask.conf /tmp/99-cmdline-ask.conf
modules.d/80base/init.sh:125:    [ -f /tmp/99-cmdline-ask.conf ] && mv /tmp/99-cmdline-ask.conf /etc/cmdline.d/99-cmdline-ask.conf
modules.d/14watchdog-modules/module-setup.sh:28:        )\"" > "${initdir}"/etc/cmdline.d/00-watchdog.conf
```

### PR DESCRIPTION
**Pull request by jozzsi**
## Changes

The main motivation of this PR is to make it easier to reason about the ordering numbers of dracut generated cmdline conf files.

Prefix almost all dracut generated cmdline conf file in the 20 ordering as the ordering is usually not significant for these cmdline conf file.

Document that 50-59 is the recommended ordering range for 3rd party cmdline conf files to make it consistent with e.g. 3rd party dracut modules recommendation.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1489

### CODE REVIEW

**Review by bdrung — DISMISSED** [review]

File: modules.d/73zipl/module-setup.sh [hunk 1]
```diff
@@ -61,6 +61,6 @@ install() {
         local _zipl
         _zipl=$(cmdline)
 
-        [[ $_zipl ]] && printf "%s\n" "$_zipl" > "${initdir}/etc/cmdline.d/91zipl.conf"
+        [[ $_zipl ]] && printf "%s\n" "$_zipl" > "${initdir}/etc/cmdline.d/20-zipl.conf"
```
Comment (mwilck) [inline modules.d/73zipl/module-setup.sh]: It looks fishy that you're using the same file name her as in install_zipl_cmdline.sh above, while previously the file names were not identical. At least a comment would be in order if you have verified that this is correct.

File: modules.d/77dracut-systemd/dracut-cmdline-ask.sh [hunk 2]
```diff
@@ -18,7 +18,7 @@ echo "Enter additional kernel command line parameter (end with ctrl-d or .)"
 # shellcheck disable=SC3045
 while read -r -p "> " ${BASH:+-e} line || [ -n "$line" ]; do
     [ "$line" = "." ] && break
-    [ -n "$line" ] && printf -- "%s\n" "$line" >> /etc/cmdline.d/99-cmdline-ask.conf
+    [ -n "$line" ] && printf -- "%s\n" "$line" >> /etc/cmdline.d/20-cmdline-ask.conf
```
Comment (mwilck) [inline modules.d/77dracut-systemd/dracut-cmdline-ask.sh]: These are not regular cmdline arguments from built-in modules. I wonder if they should remain at 99. Likewise for `dracut-cmdline` below.

File: modules.d/80base/init.sh [hunk 3]
```diff
@@ -115,14 +115,14 @@ if getarg "rd.cmdline=ask"; then
     # shellcheck disable=SC3045
     while read -r -p "> " ${BASH:+-e} line || [ -n "$line" ]; do
         [ "$line" = "." ] && break
-        echo "$line" >> /etc/cmdline.d/99-cmdline-ask.conf
```
Comment (mwilck) [inline modules.d/80base/init.sh]: Again, these don't come from built-in modules.

File: modules.d/80base/init.sh [hunk 4]
```diff
@@ -115,14 +115,14 @@ if getarg "rd.cmdline=ask"; then
...
+        echo "$line" >> /etc/cmdline.d/20-cmdline-ask.conf
     done
 fi
 
 if ! getargbool 1 'rd.hostonly'; then
-    [ -f /etc/cmdline.d/99-cmdline-ask.conf ] && mv /etc/cmdline.d/99-cmdline-ask.conf /tmp/99-cmdline-ask.conf
+    [ -f /etc/cmdline.d/20-cmdline-ask.conf ] && mv /etc/cmdline.d/20-cmdline-ask.conf /tmp/20-cmdline-ask.conf
```
Comment (mwilck) [inline modules.d/80base/init.sh]: ... and again.

**Review by mwilck — CHANGES_REQUESTED** [review]
See inline comments. This needs at least some more explanations, IMO.

File: modules.d/73zipl/module-setup.sh (hunk 1 above)
Comment (jozzsi) [reply modules.d/73zipl/module-setup.sh]: great find @mwilck . Changed this number for 19 for now instead of 20.

File: modules.d/77dracut-systemd/dracut-cmdline-ask.sh (hunk 2 above)
Comment (jozzsi) [reply modules.d/77dracut-systemd/dracut-cmdline-ask.sh]: I am not sure if this needs to stay 99, but we can discuss that in a follow-up PR. This PR is complex enough as it is. 

I reverted this back to 99.

File: modules.d/80base/init.sh (hunk 4 above)
Comment (jozzsi) [reply modules.d/80base/init.sh]: yes, done

File: modules.d/80base/init.sh (hunk 3 above)
Comment (jozzsi) [reply modules.d/80base/init.sh]: thanks. done.
