### PR TITLE
fix(dracut.sh): do not use uname to detect kernel version in a container

### LINKED ISSUE #1455: default to running for /usr/lib/modules/$kver in a container
This is a followup to https://github.com/dracut-ng/dracut-ng/pull/582#issuecomment-2294210362

Basically let's do

```
if systemd-detect-virt -c != none; then
  kver=$(cd /usr/lib/modules && echo *)
fi
```

### PR DESCRIPTION
**Pull request by jozzsi**
## Changes

A big general papercut with dracut right now in that it always assumes the kernel it's running on is the kernel to target.

This commit lets dracut to detect that it's in a container (e.g. systemd-detect-virt -c), and check for a single /usr/lib/modules/$kver directory and automatically use that kernel.

Currently this kernel version detection has three copies in the source (dracut.sh, lsinitrd.sh,test-functions). This commit keeps the logic for the three copies the same. As a follow-up commit, we should try to actually share the code for this logic instead of copying it.

CC @cgwalters 

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #1455

### CODE REVIEW

File: dracut.sh [hunk 1]
```diff
@@ -1073,7 +1073,13 @@ if [[ $regenerate_all == "yes" ]]; then
 fi
 
 if ! [[ $kernel ]]; then
-    kernel=$(uname -r)
+    if type -P systemd-detect-virt &> /dev/null && systemd-detect-virt -c &> /dev/null; then
+        # shellcheck disable=SC2012
+        kernel="$(cd /lib/modules && ls -1 | tail -1)"
```
Comment (cgwalters) [inline dracut.sh]: We're relying on the default sorting from `ls` here...which is probably fine, but *in theory* should maybe be doing some sort of version number parsing.

On the bootc side we strictly disallow multiple kernels, so it's not a concern either way.

File: dracut.sh [hunk 2]
```diff
@@ -1073,7 +1073,13 @@ if [[ $regenerate_all == "yes" ]]; then
...
+        # shellcheck disable=SC2012
+        [[ $kernel ]] || kernel="$(cd /usr/lib/modules && ls -1 | tail -1)"
```
Comment (cgwalters) [inline dracut.sh]: Do we really care about non-usrmerge systems i.e. where `/lib` isn't just a symlink to `/usr/lib`?

File: dracut.sh [hunk 3]
```diff
@@ -1073,7 +1073,13 @@ if [[ $regenerate_all == "yes" ]]; then
 fi
 
 if ! [[ $kernel ]]; then
-    kernel=$(uname -r)
+    if type -P systemd-detect-virt &> /dev/null && systemd-detect-virt -c &> /dev/null; then
```
Comment (cgwalters) [inline dracut.sh]: Perhaps worth logging something here, like:
```
    if type -P systemd-detect-virt &> /dev/null && container=systemd-detect-virt -c &> /dev/null; then
dracut_log "Detected container: $container"
```

or so?

File: dracut.sh (hunk 1 above)
Comment (jozzsi) [reply dracut.sh]: Went with ls -v here, seems a low hanging fruit and hopefully the second commit does not slow down the PR review. Thanks for the tip.

File: dracut.sh (hunk 3 above)
Comment (jozzsi) [reply dracut.sh]: Done.

File: dracut.sh (hunk 2 above)
Comment (jozzsi) [reply dracut.sh]: Fair question. Dracut CI uses Alpine to test some conditions that are relevant also for Fedora, but easier to test with Alpine - e.g. busybox compatibility (busybox is not available in CentOS).

Alpine still uses /lib/modules. I understand why this caught your eyes, but perhaps best to handle this as a separate PR. Some ideas:
 - change the order of detection as `/usr/lib/modules` is the common case
 - remove support for `/lib/modules` and add a workaround in the Alpine CI container with a sym link - this would break Alpine dracut packaging if Alpine packaging decide to run tests as part of packaging

Comment (cgwalters) [reply dracut.sh]: From my PoV a cleanup here should probably happen after the code dedup you mention first. I think it's OK as is.

File: dracut.sh [hunk 4]
```diff
@@ -1073,7 +1073,14 @@ if [[ $regenerate_all == "yes" ]]; then
 fi
 
 if ! [[ $kernel ]]; then
-    kernel=$(uname -r)
+    if type -P systemd-detect-virt &> /dev/null && container=$(systemd-detect-virt -c) &> /dev/null; then
+        printf "%s\n" "dracut[W]: Detected container: $container" >&2
```
Comment (bdrung) [inline dracut.sh]: Why print the detected container as warning?

**Comment by bdrung** [comment]
What I would like to see as follow-up PR: Move the code into a function that is identical everywhere.

File: dracut.sh (hunk 4 above)
Comment (jozzsi) [reply dracut.sh]: https://github.com/dracut-ng/dracut-ng/pull/1456#discussion_r2211222252

CC @cgwalters

Comment (cgwalters) [reply dracut.sh]: I don't strongly think we need to log at all if that's the question, but I think @bdrung is more asking "why isn't this `dinfo`" right?

We already log a whole lot of stuff at `dinfo` level.

Comment (jozzsi) [reply dracut.sh]: Oh, I see. Changed to `dinfo`.
