### PR TITLE
fix: load more kernel modules in sloppy hostonly mode

### LINKED ISSUE #748: Please support hostonly mode with full portability
**Describe the enhancement**

In Ubuntu, initramfs-tools builds portable initrds by default. We want that user can replace hardware (e.g. the graphics card, keyboard) and still be able to boot. Taking a disk from one machine, plug it into a different machine, and boot should work out of the box.

That was the reason Ubuntu sets `hostonly=false`. Pull request #746 and issue #674 revealed that I misunderstood the `no-hostonly` mode and I had a lack of knowledge. The man page says in "Boot parameters":

> An initramfs generated without the "hostonly" mode, does not contain any system configuration files (except for some special exceptions), so the configuration has to be done on the kernel command line.

But as you can see in #746 we want to honor the system configuration files in Ubuntu.

The usage section of the man page says:

> If you want to create lighter, smaller initramfs images, you may want to specify the --hostonly or -H option. Using this option, the resulting image will contain only those dracut modules, kernel modules and filesystems, which are needed to boot this specific machine. This has the drawback, that you can’t put the disk on another controller or machine, and that you can’t switch to another root filesystem, without recreating the initramfs image. The usage of the --hostonly option is only for experts and you will have to keep the broken pieces.

As mentioned above Ubuntu wants to support putting the disk on another controller or machine.

There is `--hostonly-mode` that can be `strict` or `sloppy`.

> In "sloppy" host-only mode, extra drivers and modules will be installed, so minor hardware change won’t make the image unbootable (e.g. changed keyboard), and the image is still portable among similar hosts.

I am proposing to add another mode, e.g. `full` that will support major hardware changes. Then Ubuntu will switch to this mode.

### PR DESCRIPTION
**Pull request by jozzsi**
## Changes

When `hostonly_mode` is set (e.g. to either `sloppy` or `strict`) `instmods` consults the host for currently loaded kernel modules and refuses to copy the Linux kernel module into the generated initramfs unless the kernel module is already loaded on the host.

Let's set `hostonly` variable explicitly to handle `sloppy` better before calling `instmods`.

For compatibility, we should not change the default in the `instmods` function itself.

The `hostonly=$(optional_hostonly) instmods` pattern is already used in some modules - e.g. https://github.com/dracut-ng/dracut-ng/blob/main/modules.d/95nfs/module-setup.sh#L41

See also https://github.com/dracut-ng/dracut-ng/blob/main/dracut-init.sh#L380 

CC @dalto8  @ArrayBolt3  @bdrung @LaszloGombos @Conan-Kudo 

## Checklist
- [x] I have tested it locally
- [x] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #748 https://github.com/dracutdevs/dracut/issues/2687

### CODE REVIEW

File: modules.d/45simpledrm/module-setup.sh [hunk 1]
```diff
@@ -8,17 +8,17 @@ check() {
 # called by dracut
 installkernel() {
     # Include simple DRM driver
-    instmods simpledrm
+    hostonly='' instmods simpledrm
 
-    if [[ $hostonly ]]; then
+    if [[ $hostonly_mode != "strict" ]]; then
```
Comment (ArrayBolt3) [inline modules.d/45simpledrm/module-setup.sh:13]: I think the `!=` is supposed to be an `=` here. You want to restrict the modules in strict mode, but not in sloppy mode and definitely not in `hostonly=no` mode. Right now this will run even when `hostonly=no` is set, if I'm understanding correctly.

**Comment by ArrayBolt3** [comment]
This works for me in a Trixie virtual machine (I can boot an encrypted installation), but I also am now for the first time running into https://github.com/dracutdevs/dracut/issues/723 for some reason. Unsure if the two are related.

**Comment by ArrayBolt3** [comment]
OK, nevermind about the bug I ran into, it must be user error because even Debian's vanilla dracut package is doing it to me now.

**Comment by Conan-Kudo** [comment]
@ArrayBolt3 @bdrung could you test to see if this makes things work the way you expect it to?

**Comment by ArrayBolt3** [comment]
Will give it another check probably later today.

**Comment by ArrayBolt3** [comment]
@Conan-Kudo @jozzsi Works fine for me in a Debian Trixie XFCE VM.

**Review by Conan-Kudo — APPROVED** [review]
I don't see any reason not to land this now. This PR still makes me nervous, but let's go for it anyway.
